set_property PACKAGE_PIN F16 [get_ports {gpio_led[7]}]
set_property PACKAGE_PIN E18 [get_ports {gpio_led[6]}]
set_property PACKAGE_PIN G19 [get_ports {gpio_led[5]}]
set_property PACKAGE_PIN AE26 [get_ports {gpio_led[4]}]
set_property PACKAGE_PIN AB9 [get_ports {gpio_led[3]}]
set_property PACKAGE_PIN AC9 [get_ports {gpio_led[2]}]
set_property PACKAGE_PIN AA8 [get_ports {gpio_led[1]}]
set_property PACKAGE_PIN AB8 [get_ports {gpio_led[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_led[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_led[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_led[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_led[4]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_led[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_led[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_led[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_led[0]}]
set_property PACKAGE_PIN T26 [get_ports {phy_rxd[6]}]
set_property PACKAGE_PIN T28 [get_ports {phy_rxd[7]}]
set_property PACKAGE_PIN T27 [get_ports {phy_rxd[5]}]
set_property PACKAGE_PIN R19 [get_ports {phy_rxd[4]}]
set_property PACKAGE_PIN U28 [get_ports {phy_rxd[3]}]
set_property PACKAGE_PIN T25 [get_ports {phy_rxd[2]}]
set_property PACKAGE_PIN U25 [get_ports {phy_rxd[1]}]
set_property PACKAGE_PIN U30 [get_ports {phy_rxd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_rxd[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_rxd[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_rxd[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_rxd[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_rxd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_rxd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_rxd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_rxd[0]}]
set_property PACKAGE_PIN J28 [get_ports {phy_txd[7]}]
set_property PACKAGE_PIN L30 [get_ports {phy_txd[6]}]
set_property PACKAGE_PIN K26 [get_ports {phy_txd[5]}]
set_property PACKAGE_PIN J26 [get_ports {phy_txd[4]}]
set_property PACKAGE_PIN L28 [get_ports {phy_txd[3]}]
set_property PACKAGE_PIN M29 [get_ports {phy_txd[2]}]
set_property PACKAGE_PIN N25 [get_ports {phy_txd[1]}]
set_property PACKAGE_PIN N27 [get_ports {phy_txd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_txd[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_txd[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_txd[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_txd[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_txd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_txd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_txd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_txd[0]}]
set_property PACKAGE_PIN W19 [get_ports phy_col]
set_property PACKAGE_PIN R30 [get_ports phy_crs]
set_property PACKAGE_PIN R23 [get_ports phy_mdc]
set_property PACKAGE_PIN J21 [get_ports phy_mdio]
set_property PACKAGE_PIN L20 [get_ports phy_rstn]
set_property PACKAGE_PIN U27 [get_ports phy_rxclk]
set_property PACKAGE_PIN R28 [get_ports phy_rxctl_rxdv]
set_property PACKAGE_PIN V26 [get_ports phy_rxer]
set_property PACKAGE_PIN K30 [get_ports phy_txc_gtxclk]
set_property PACKAGE_PIN M28 [get_ports phy_txclk]
set_property PACKAGE_PIN M27 [get_ports phy_txctl_txen]
set_property PACKAGE_PIN N29 [get_ports phy_txer]
set_property IOSTANDARD LVCMOS15 [get_ports cpu_reset]
set_property PACKAGE_PIN AB7 [get_ports cpu_reset]
set_property PACKAGE_PIN Y28 [get_ports {gpio_dip_sw[3]}]
set_property PACKAGE_PIN AA28 [get_ports {gpio_dip_sw[2]}]
set_property PACKAGE_PIN W29 [get_ports {gpio_dip_sw[1]}]
set_property PACKAGE_PIN Y29 [get_ports {gpio_dip_sw[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_dip_sw[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_dip_sw[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_dip_sw[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_dip_sw[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports phy_col]
set_property IOSTANDARD LVCMOS25 [get_ports phy_crs]
set_property IOSTANDARD LVCMOS25 [get_ports phy_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports phy_mdio]
set_property IOSTANDARD LVCMOS25 [get_ports phy_rstn]
set_property IOSTANDARD LVCMOS25 [get_ports phy_rxclk]
set_property IOSTANDARD LVCMOS25 [get_ports phy_rxctl_rxdv]
set_property IOSTANDARD LVCMOS25 [get_ports phy_rxer]
set_property IOSTANDARD LVCMOS25 [get_ports phy_txc_gtxclk]
set_property IOSTANDARD LVCMOS25 [get_ports phy_txclk]
set_property IOSTANDARD LVCMOS25 [get_ports phy_txctl_txen]
set_property IOSTANDARD LVCMOS25 [get_ports phy_txer]

set_property PACKAGE_PIN AD12 [get_ports sysclk_p]
set_property PACKAGE_PIN AD11 [get_ports sysclk_n]
set_property IOSTANDARD LVDS [get_ports sysclk_p]
set_property IOSTANDARD LVDS [get_ports sysclk_n]

#
# SiTCP timing constrainsts
# ref., http://openit.kek.jp/tips/member/fpga-pcb/fpga/741101568
#
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX10Data*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX11Data*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX12Data*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX13Data*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX14Data*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX15Data*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX16Data*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX17Data*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX18Data*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX19Data*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1AData*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1BData*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/BBT_SiTCP_RST/resetReq*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/GMII/GMII_TXBUF/memRdReq*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/GMII/GMII_TXBUF/orRdAct*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/GMII/GMII_TXBUF/dlyBank0LastWrAddr*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/GMII/GMII_TXBUF/dlyBank1LastWrAddr*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/GMII/GMII_TXBUF/muxEndTgl]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/GMII/GMII_RXBUF/cmpWrAddr*]

set_property PACKAGE_PIN AE28 [get_ports spi_sclk25]
set_property PACKAGE_PIN AF28 [get_ports spi_sdata25]
set_property PACKAGE_PIN AF30 [get_ports dac_sdo25]
set_property PACKAGE_PIN AE30 [get_ports dac_n_en25]
set_property PACKAGE_PIN AC24 [get_ports adc_sdo25]
set_property PACKAGE_PIN AC22 [get_ports adc_n_en25]
set_property IOSTANDARD LVCMOS25 [get_ports spi_sclk25]
set_property IOSTANDARD LVCMOS25 [get_ports spi_sdata25]
set_property IOSTANDARD LVCMOS25 [get_ports dac_sdo25]
set_property IOSTANDARD LVCMOS25 [get_ports dac_n_en25]
set_property IOSTANDARD LVCMOS25 [get_ports adc_sdo25]
set_property IOSTANDARD LVCMOS25 [get_ports adc_n_en25]

#
# ads4249 I/O
#
set_property PACKAGE_PIN AG25 [get_ports {cha_p[6]}]
set_property PACKAGE_PIN AK20 [get_ports {cha_p[5]}]
set_property PACKAGE_PIN AG22 [get_ports {cha_p[4]}]
set_property PACKAGE_PIN AH21 [get_ports {cha_p[3]}]
set_property PACKAGE_PIN AG20 [get_ports {cha_p[2]}]
set_property PACKAGE_PIN AF20 [get_ports {cha_p[1]}]
set_property PACKAGE_PIN AE23 [get_ports {cha_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {cha_p[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {cha_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {cha_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {cha_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {cha_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {cha_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {cha_p[0]}]
set_property PACKAGE_PIN AD21 [get_ports {chb_p[6]}]
set_property PACKAGE_PIN AB24 [get_ports {chb_p[5]}]
set_property PACKAGE_PIN AA20 [get_ports {chb_p[4]}]
set_property PACKAGE_PIN AE25 [get_ports {chb_p[3]}]
set_property PACKAGE_PIN AJ24 [get_ports {chb_p[2]}]
set_property PACKAGE_PIN AK23 [get_ports {chb_p[1]}]
set_property PACKAGE_PIN AJ22 [get_ports {chb_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {chb_p[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {chb_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {chb_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {chb_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {chb_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {chb_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {chb_p[0]}]
set_property PACKAGE_PIN AE24 [get_ports clk_ab_n]
set_property IOSTANDARD LVDS_25 [get_ports clk_ab_p]
set_property IOSTANDARD LVDS_25 [get_ports clk_ab_n]

set_property PACKAGE_PIN AD24 [get_ports adc_reset25]
set_property IOSTANDARD LVCMOS25 [get_ports adc_reset25]
set_property PACKAGE_PIN AD22 [get_ports txenable25]
set_property IOSTANDARD LVCMOS25 [get_ports txenable25]



#create_clock -period 5.000 -name clk_ab_p -waveform {0.000 2.500} [get_ports clk_ab_p]

set_property PACKAGE_PIN G12 [get_ports gpio_sw_c]
set_property IOSTANDARD LVCMOS25 [get_ports gpio_sw_c]
set_property PACKAGE_PIN AG5 [get_ports gpio_sw_e]
set_property IOSTANDARD LVCMOS15 [get_ports gpio_sw_n]
set_property IOSTANDARD LVCMOS15 [get_ports gpio_sw_e]
set_property PACKAGE_PIN AA12 [get_ports gpio_sw_n]
set_property PACKAGE_PIN AB12 [get_ports gpio_sw_s]
set_property IOSTANDARD LVCMOS15 [get_ports gpio_sw_s]
set_property PACKAGE_PIN AC6 [get_ports gpio_sw_w]
set_property IOSTANDARD LVCMOS15 [get_ports gpio_sw_w]

#
# DAC3283 I/O
#
set_property PACKAGE_PIN AB27 [get_ports {dout_p[7]}]
set_property PACKAGE_PIN AD27 [get_ports {dout_p[6]}]
set_property PACKAGE_PIN AJ26 [get_ports {dout_p[5]}]
set_property PACKAGE_PIN AF26 [get_ports {dout_p[4]}]
set_property PACKAGE_PIN AH26 [get_ports {dout_p[3]}]
set_property PACKAGE_PIN AG30 [get_ports {dout_p[2]}]
set_property PACKAGE_PIN AC26 [get_ports {dout_p[1]}]
set_property PACKAGE_PIN AK29 [get_ports {dout_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {dout_p[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {dout_p[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {dout_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {dout_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {dout_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {dout_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {dout_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {dout_p[0]}]
set_property PACKAGE_PIN AG27 [get_ports dclk_p]
set_property PACKAGE_PIN AJ27 [get_ports frame_p]
set_property IOSTANDARD LVDS_25 [get_ports dclk_p]
set_property IOSTANDARD LVDS_25 [get_ports frame_p]

set_property DIFF_TERM FALSE [get_ports sysclk_p]
set_property DIFF_TERM FALSE [get_ports sysclk_n]

# set false path by shugo
set_false_path -through [get_nets {gpio_led[*] gpio_led_OBUF[*]}]
set_false_path -through [get_nets {gpio_dip_sw[*] gpio_dip_sw[*]_IBUF}]
#set_false_path -through [get_nets gpio_sw_*]
#set_false_path -through [get_nets ]
set_false_path -from [get_clocks clk_out1_system_clock] -to [get_clocks clk_out1_adc_clock]
set_false_path -from [get_clocks clk_out1_system_clock] -to [get_clocks clk_out2_system_clock]

set_false_path -from [get_pins {IQ_Reader_inst/ds_rate_reg[*]/C}] -to [get_pins {Demodulation[*].I_Data_Downsampler_inst/counter_reg[*]/R}]
set_false_path -from [get_pins {IQ_Reader_inst/ds_rate_reg[*]/C}] -to [get_pins {Demodulation[*].Q_Data_Downsampler_inst/counter_reg[*]/R}]
